Add-remove
tylher/To-do-List pull request #3
Opened 2022-03-23 16:03 UTC by tylher

### Add and Remove Item Functionalities

- Made Use of classes
- Created modules in the source folder and imported them into the index.js
- Added addItem method to add items to the list
- Added a check method to enable users to check the box when a task is completed
- Implemented a remove method to remove all completed tasks.
- Displayed the to-do list using a method 
- Stored and updated changes in the local storage

2022-03-23 16:56 UTC, nicupop729 requested changes
# STATUS: Required Changes ♻️

Hi @tylher, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

### Required Changes ♻️

- [ ] Please consider to implement a function for editing a task in the todo list;
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 16:56 UTC, nicupop729 commented on src/toDo.js
> +  }
Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
In your project, the indexes are not updating after an item is deleted. This could lead to the repetition of indexes in your list of tasks. 
Here is an example from your project:
![image](https://user-images.githubusercontent.com/83596135/159753716-e0fd2dd3-7650-4244-84c6-218f1e0f32fb.png)

- [x] Please implement the updating of indexes in your code, so they represent the current list order and are unique;

2022-03-23 20:28 UTC, tylher commented on src/toDo.js
> +  }
@nicupop729 thank you, I will make the necessary changes.

2022-03-24 12:33 UTC, BenMukebo requested changes
### Hi ** @tylher, **

You did a great job on adding the changes as mentioned by the previous reviewer, 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/S01xbtsDD5NSMK3oYV/giphy.gif"/>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Good commit messages ✔️ 

 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 12:33 UTC, BenMukebo commented on src/toDo.js
>        this.listHolder.innerHTML = '';
- [ ] Please implement the remove function to remove a single particular item from the list, actually, the only working is `remveAllCompleted`, kindly take a look at [this](https://www.youtube.com/watch?v=AcUd-_Yjjqg)
  - the selected item should have a `line through` it showing that it is completed
  - you may be able to delete that particular item from the list.
  
<img width="632" alt="select" src="https://user-images.githubusercontent.com/79058364/159916314-a8172b9c-f209-4732-a3de-b4b595eb7aa2.png">

2022-03-24 18:52 UTC, nicupop729 approved these changes
<h1>Status: Approved 🥇 ✔</h1>
Hi @tylher,

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

**One small thing I noticed is that after you unmark a task, it remains with the line-throgh. I recommend you to try to figure that out, how to take that line-throgh back.**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 19:54 UTC, merged